dist: focal
os:
- linux

language: python

jobs:
  include:
  - name: Fixed version of cwltool
    python: 3.8
    install:
    - pip install --upgrade cwltool==3.0.20200710214758
    script: find . -name "*.cwl" | xargs -n 1 cwltool --validate
  - name: Latest version of cwltool
    python: 3.8
    install:
    - pip install --upgrade cwltool
    script: find . -name "*.cwl" | xargs -n 1 cwltool --validate

branches:
  only:
  - main
notifications:
  email: false