cwlVersion: v1.0
class: Workflow


requirements:
  - class: SubworkflowFeatureRequirement
  - class: StepInputExpressionRequirement
  - class: InlineJavascriptRequirement
  - class: MultipleInputFeatureRequirement


inputs:

  indices_folder:
    type: Directory
    doc: "Cell Ranger generated genome indices folder"

  fastq_file_r1:
    type: File
    doc: "FASTQ file R1 (optionally compressed)"

  fastq_file_r2:
    type: File
    doc: "FASTQ file R2 (optionally compressed)"

  expect_cells:
    type: int?
    default: 3000
    doc: "Expected number of recovered cells"

  force_expect_cells:
    type: boolean?
    default: false
    doc: |
      Force pipeline to use the expected number of recovered cell.
      The value provided in expect_cells will be sent to Cell Ranger
      Count as --force-cells. The latter will bypass the cell detection
      algorithm. Use this if the number of cells estimated by Cell Ranger
      is not consistent with the barcode rank plot.

  include_introns:
    type: boolean?
    default: false
    doc: |
      Count reads mapping to intronic regions. This may improve sensitivity
      for samples with a significant amount of pre-mRNA molecules, such as nuclei.

  threads:
    type: int?
    default: 4
    doc: "Number of threads for those steps that support multithreading"

  memory_limit:
    type: int?
    default: 20
    doc: "Maximum memory used (GB). The same will be applied to virtual memory"


outputs:

  fastqc_report_fastq_r1:
    type: File
    outputSource: run_fastqc_for_fastq_r1/html_file
    doc: "FastqQC report for FASTQ file R1"

  fastqc_report_fastq_r2:
    type: File
    outputSource: run_fastqc_for_fastq_r2/html_file
    doc: "FastqQC report for FASTQ file R2"

  web_summary_report:
    type: File
    outputSource: generate_counts_matrix/web_summary_report
    doc: "Cell Ranger summary"

  metrics_summary_report:
    type: File
    outputSource: generate_counts_matrix/metrics_summary_report
    doc: "Run summary metrics in CSV format"

  possorted_genome_bam_bai:
    type: File
    outputSource: generate_counts_matrix/possorted_genome_bam_bai
    doc: "Aligned to the genome indexed reads BAM+BAI files"

  filtered_feature_bc_matrix_folder:
    type: File
    outputSource: compress_filtered_feature_bc_matrix_folder/compressed_folder
    doc: "Compressed folder with filtered feature-barcode matrices in MEX format"

  filtered_feature_bc_matrix_h5:
    type: File
    outputSource: generate_counts_matrix/filtered_feature_bc_matrix_h5
    doc: "Filtered feature-barcode matrices in HDF5 format"
  
  raw_feature_bc_matrices_folder:
    type: File
    outputSource: compress_raw_feature_bc_matrices_folder/compressed_folder
    doc: "Compressed folder with unfiltered feature-barcode matrices in MEX format"

  raw_feature_bc_matrices_h5:
    type: File
    outputSource: generate_counts_matrix/raw_feature_bc_matrices_h5
    doc: "Unfiltered feature-barcode matrices in HDF5 format"

  secondary_analysis_report_folder:
    type: File
    outputSource: compress_secondary_analysis_report_folder/compressed_folder
    doc: "Compressed folder with secondary analysis results"

  molecule_info_h5:
    type: File
    outputSource: generate_counts_matrix/molecule_info_h5
    doc: "Molecule-level information for aggregating samples into larger datasets"

  loupe_browser_track:
    type: File
    outputSource: generate_counts_matrix/loupe_browser_track
    doc: "Loupe Browser visualization and analysis file"

  collected_statistics:
    type: File
    outputSource: collect_statistics/collected_statistics
    doc: "Collected statistics in Markdown format"

  generate_counts_matrix_stdout_log:
    type: File
    outputSource: generate_counts_matrix/stdout_log
    doc: "Stdout log generated by cellranger count"

  generate_counts_matrix_stderr_log:
    type: File
    outputSource: generate_counts_matrix/stderr_log
    doc: "Stderr log generated by cellranger count"

  compressed_html_data_folder:
    type: File
    outputSource: compress_html_data_folder/compressed_folder
    doc: "Compressed folder with CellBrowser formatted results"

  html_data_folder:
    type: Directory
    outputSource: cellbrowser_build/html_data
    doc: "Folder with not compressed CellBrowser formatted results"

  cellbrowser_report:
    type: File
    outputSource: cellbrowser_build/index_html_file
    doc: "CellBrowser formatted Cellranger report"


steps:

  extract_fastq_r1:
    run: ../tools/extract-fastq.cwl
    in:
      compressed_file: fastq_file_r1
    out:
    - fastq_file

  extract_fastq_r2:
    run: ../tools/extract-fastq.cwl
    in:
      compressed_file: fastq_file_r2
    out:
    - fastq_file

  run_fastqc_for_fastq_r1:
    run: ../tools/fastqc.cwl
    in:
      reads_file: extract_fastq_r1/fastq_file
      threads: threads
    out:
    - html_file

  run_fastqc_for_fastq_r2:
    run: ../tools/fastqc.cwl
    in:
      reads_file: extract_fastq_r2/fastq_file
      threads: threads
    out:
    - html_file

  generate_counts_matrix:
    run: ../tools/cellranger-count.cwl
    in:
      fastq_file_r1: extract_fastq_r1/fastq_file
      fastq_file_r2: extract_fastq_r2/fastq_file
      indices_folder: indices_folder
      expect_cells:
        source: [expect_cells, force_expect_cells]
        valueFrom: $(self[1]?null:self[0])
      force_cells:
        source: [expect_cells, force_expect_cells]
        valueFrom: $(self[1]?self[0]:null)
      include_introns: include_introns
      threads: threads
      memory_limit: memory_limit
      virt_memory_limit: memory_limit
    out:
    - web_summary_report
    - metrics_summary_report
    - possorted_genome_bam_bai
    - filtered_feature_bc_matrix_folder
    - filtered_feature_bc_matrix_h5
    - raw_feature_bc_matrices_folder
    - raw_feature_bc_matrices_h5
    - secondary_analysis_report_folder
    - molecule_info_h5
    - loupe_browser_track
    - stdout_log
    - stderr_log

  compress_filtered_feature_bc_matrix_folder:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: generate_counts_matrix/filtered_feature_bc_matrix_folder
    out:
    - compressed_folder

  compress_raw_feature_bc_matrices_folder:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: generate_counts_matrix/raw_feature_bc_matrices_folder
    out:
    - compressed_folder

  compress_secondary_analysis_report_folder:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: generate_counts_matrix/secondary_analysis_report_folder
    out:
    - compressed_folder

  collect_statistics:
    run:
      cwlVersion: v1.0
      class: CommandLineTool
      hints:
      - class: DockerRequirement
        dockerPull: rackspacedot/python37
      inputs:
        script:
          type: string?
          default: |
            #!/usr/bin/env python3
            import sys, csv
            with open(sys.argv[1], "r") as input_stream:
              with open("collected_statistics.md", "w") as output_stream:
                output_stream.write("### Cell Ranger Statistics\n")
                keys, values = None, None
                for i, row in enumerate(csv.reader(input_stream)):
                  if i==0:
                    keys = row
                  else:
                    values = row
                for k,v in zip(keys, values):
                  output_stream.write("- "+k+": "+v+"\n")
          inputBinding:
            position: 5
        metrics_summary_report:
          type: File
          inputBinding:
            position: 6
      outputs:
        collected_statistics:
          type: File
          outputBinding:
            glob: "*"
      baseCommand: ["python3", "-c"]
    in:
      metrics_summary_report: generate_counts_matrix/metrics_summary_report
    out:
    - collected_statistics

  cellbrowser_build:
    run: ../tools/cellbrowser-build-cellranger.cwl
    in:
      secondary_analysis_report_folder: generate_counts_matrix/secondary_analysis_report_folder
      filtered_feature_bc_matrix_folder: generate_counts_matrix/filtered_feature_bc_matrix_folder
    out:
    - html_data
    - index_html_file

  compress_html_data_folder:
    run: ../tools/tar-compress.cwl
    in:
      folder_to_compress: cellbrowser_build/html_data
    out:
    - compressed_folder


$namespaces:
  s: http://schema.org/

$schemas:
- https://github.com/schemaorg/schemaorg/raw/main/data/releases/11.01/schemaorg-current-http.rdf

label: "Cell Ranger Count Gene Expression"
s:name: "Cell Ranger Count Gene Expression"
s:alternateName: "Counts gene expression for a single library"

s:downloadUrl: https://raw.githubusercontent.com/Barski-lab/scRNA-Seq-Analysis/master/workflows/cellranger-count.cwl
s:codeRepository: https://github.com/Barski-lab/scRNA-Seq-Analysis
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:misha.kotliar@gmail.com
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898


doc: |
  Cell Ranger Count Gene Expression
  =================================

  Counts gene expression for a single library.